export enum EquipmentType {
  Weapon = '무기',
  SubWeapon = '보조무기',
  Emblem = '엠블렘',
  Hat = '모자',
  Top = '상의',
  Bottom = '하의',
  Shoes = '신발',
  Gloves = '장갑',
  Cape = '망토',
  Belt = '벨트',
  Shoulder = '어깨장식',
  Face = '얼굴장식',
  Eye = '눈장식',
  Earring = '귀걸이',
  Ring = '반지',
  Pendant = '목걸이',
  Heart = '기계심장',
}

export interface PotentialOption {
  name: string;  // 옵션 이름
  englishName: string; // 파싱용 영문 이름 포맷
}

// 각 장비별로 가능한 잠재능력 옵션 정의
export const EquipmentPotentialOptions: Record<EquipmentType, PotentialOption[]> = {
  [EquipmentType.Weapon]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '공격력%', englishName: 'ATT +{value}%' },
    { name: '마력%', englishName: 'Magic ATT +{value}%' },
    { name: '데미지%', englishName: 'Damage +{value}%' },
    { name: '보스 몬스터 공격 시 데미지%', englishName: 'Boss Monster Damage +{value}%' },
    { name: '몬스터 방어율 무시%', englishName: 'Ignore Monster DEF +{value}%' },
  ],

  [EquipmentType.SubWeapon]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '공격력%', englishName: 'ATT +{value}%' },
    { name: '마력%', englishName: 'Magic ATT +{value}%' },
    { name: '데미지%', englishName: 'Damage +{value}%' },
    { name: '보스 몬스터 공격 시 데미지%', englishName: 'Boss Monster Damage +{value}%' },
    { name: '몬스터 방어율 무시%', englishName: 'Ignore Monster DEF +{value}%' },
  ],

  [EquipmentType.Emblem]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '공격력%', englishName: 'ATT +{value}%' },
    { name: '마력%', englishName: 'Magic ATT +{value}%' },
    { name: '데미지%', englishName: 'Damage +{value}%' },
    { name: '몬스터 방어율 무시%', englishName: 'Ignore Monster DEF +{value}%' },
  ],

  [EquipmentType.Hat]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '재사용 대기시간 감소', englishName: 'Skill Cooldown -{value}sec (-10% for under 10 sec, minimum cooldown 5 sec)' },
  ],

  [EquipmentType.Ring]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '메소 획득량%', englishName: 'Meso Obtained%' },
    { name: '아이템 드롭률%', englishName: 'Item Drop Rate%' },
  ],

  [EquipmentType.Top]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],

  [EquipmentType.Bottom]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Shoes]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Gloves]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '크리티컬 데미지%', englishName: 'Critical Damage +{value}%' },
    // { name: '오토 스틸%', englishName: 'Auto Steal Chance +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Cape]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Belt]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Shoulder]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Face]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '메소 획득량%', englishName: 'Meso Obtained%' },
    { name: '아이템 드롭률%', englishName: 'Item Drop Rate%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Eye]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '메소 획득량%', englishName: 'Meso Obtained%' },
    { name: '아이템 드롭률%', englishName: 'Item Drop Rate%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Earring]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '메소 획득량%', englishName: 'Meso Obtained%' },
    { name: '아이템 드롭률%', englishName: 'Item Drop Rate%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Pendant]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: '메소 획득량%', englishName: 'Meso Obtained%' },
    { name: '아이템 드롭률%', englishName: 'Item Drop Rate%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
  [EquipmentType.Heart]: [
    { name: 'STR%', englishName: 'STR +{value}%' },
    { name: 'DEX%', englishName: 'DEX +{value}%' },
    { name: 'INT%', englishName: 'INT +{value}%' },
    { name: 'LUK%', englishName: 'LUK +{value}%' },
    { name: '올스탯%', englishName: 'All Stats +{value}%' },
    { name: 'MaxHP%', englishName: 'MaxHP +{value}%' },
    { name: 'MaxMP%', englishName: 'MaxMP +{value}%' },
  ],
};
